/* Generated by `make contracts`; do not edit by hand. Verify with `make contracts-check`. Canonical source: proxyloop_contracts. */

/**
 * Canonical Phase 00B wire contracts generated from the framework-independent Pydantic package.
 */
export type ProxyLoopContractDocument =
  | Case
  | ConsumerGoal
  | Constraint
  | BillSnapshot
  | FactLedger
  | StrategyPacket
  | FastTurnDecision
  | ProviderOffer
  | ActionIntent
  | ApprovalRequest
  | Evidence
  | CompletionDecision
  | ModelTrace;
export type AddOns = string[];
export type CapturedAt = string;
export type CaseId = string;
export type ContractType = "bill_snapshot";
export type EvidenceIds = string[];
export type AmountMinor = number;
export type Currency = string;
export type LineItemCategory = "service" | "addon" | "fee" | "tax" | "credit";
export type Name = string;
export type LineItems = LineItem[];
export type Revision = number;
export type SchemaVersion = "1.0";
export type SnapshotId = string;
export type TermMonths = number;
export type DataMegabytes = number;
export type SmsCount = number;
export type VoiceMinutes = number;
export type CaseId1 = string;
export type ConstraintSetRevision = number;
export type CaseId2 = string;
export type ConstraintClassification = "hard" | "soft";
export type ConstraintId = string;
export type ContractType1 = "constraint";
export type Priority = number | null;
export type Revision1 = number;
export type SchemaVersion1 = "1.0";
export type Source = string;
export type Statement = string;
export type ValidFrom = string;
export type ValidUntil = string | null;
export type Constraints = Constraint[];
export type ConsumerId = string;
export type ContractType2 = "case";
export type CreatedAt = string;
export type ActionType =
  "send_message" | "request_clarification" | "disclose_information" | "accept_offer" | "end_interaction";
export type AllowedActions = ActionType[];
export type AllowedDisclosures = string[];
export type ApprovalRequiredActions = ActionType[];
export type CaseId3 = string;
export type ContractType3 = "consumer_goal";
export type CreatedAt1 = string;
export type Deadline = string | null;
export type DesiredOutcome = string;
export type ForbiddenChanges = string[];
export type GoalId = string;
export type RequiredFeatures = string[];
export type Revision2 = number;
export type SchemaVersion2 = "1.0";
export type UpdatedAt = string;
export type CasePhase =
  "initiated" | "strategy" | "negotiating" | "awaiting_approval" | "candidate_complete" | "complete" | "closed";
export type Revision3 = number;
export type SchemaVersion3 = "1.0";
export type UpdatedAt1 = string;
export type CaseId4 = string;
export type ContractType4 = "fact_ledger";
export type CreatedAt2 = string;
export type Confidence = number;
export type EvidenceIds1 = string[];
export type FactId = string;
export type Key = string;
export type RecordedAt = string;
export type SourceMessageId = string | null;
export type FactStatus = "candidate" | "verified" | "rejected";
export type FactValue = Money | string | number | boolean;
export type Entries = FactRecord[];
export type LedgerId = string;
export type Revision4 = number;
export type SchemaVersion4 = "1.0";
export type UpdatedAt2 = string;
export type AllowedDisclosures1 = string[];
export type ApprovalRequiredDisclosures = string[];
export type CaseId5 = string;
export type CaseRevision = number;
export type ConcessionLadder = string[];
export type ContractType5 = "strategy_packet";
export type CreatedAt3 = string;
export type CurrentSubgoal = string;
export type EscalationConditions = string[];
export type ExpiresAt = string;
export type FactLedgerRevision = number;
export type FallbackOutcomes = string[];
export type HardConstraintIds = string[];
export type PrimaryObjective = string;
export type RankedPreferenceIds = string[];
export type ReplanConditions = string[];
export type Description = string;
export type EvidenceType = "provider_message" | "provider_event" | "confirmation" | "bill" | "simulator_transition";
export type RequiredCompletionEvidence = EvidenceRequirement[];
export type Revision5 = number;
export type SchemaVersion5 = "1.0";
export type StrategyId = string;
export type ApprovalRequired = boolean;
export type AuthorizationState = "proposed";
export type CaseId6 = string;
export type CaseRevision1 = number;
export type ConstraintSetRevision1 = number;
export type ContractType6 = "action_intent";
export type CreatedAt4 = string;
export type ExpiresAt1 = string | null;
export type IdempotencyKey = string;
export type IntentId = string;
export type Name1 = string;
export type Value = string;
export type MaterialTerms = MaterialTerm[];
export type MaterialTermsHash = string;
export type OfferId = string;
export type OfferRevision = number;
export type Revision6 = number;
export type SchemaVersion6 = "1.0";
export type StrategyId1 = string;
export type StrategyRevision = number;
export type CaseId7 = string;
export type CaseRevision2 = number;
export type EvidenceMessageIds = string[];
export type Status = "not_done" | "candidate";
export type ContractType7 = "fast_turn_decision";
export type CreatedAt5 = string;
export type DecisionId = string;
export type DialogueAct = "clarify" | "counter" | "confirm" | "challenge" | "escalate" | "close";
export type Confidence1 = number;
export type Key1 = string;
export type SourceMessageId1 = string;
export type Status1 = "candidate";
export type FactUpdates = FactUpdate[];
export type Needed = boolean;
export type ReasonCode = string;
export type ResponseText = string;
export type SchemaVersion7 = "1.0";
export type StrategyId2 = string;
export type StrategyRevision1 = number;
export type CaseId8 = string;
export type ContractType8 = "provider_offer";
export type CreatedAt6 = string;
export type EvidenceIds2 = string[];
export type ExpiresAt2 = string;
export type Features = string[];
export type Fees = LineItem[];
export type OfferId1 = string;
export type ProviderId = string;
export type Revision7 = number;
export type SchemaVersion8 = "1.0";
export type TermMonths1 = number;
export type ActionIntentId = string;
export type ActionIntentRevision = number;
export type ApprovalId = string;
export type CaseId9 = string;
export type CaseRevision3 = number;
export type ConstraintSetRevision2 = number;
export type ContractType9 = "approval_request";
export type DecidedAt = string | null;
export type ApprovalDecision = "pending" | "approved" | "rejected" | "expired";
export type ExpiresAt3 = string;
export type MaterialTermsHash1 = string;
export type RequestedAt = string;
export type Revision8 = number;
export type SchemaVersion9 = "1.0";
export type StrategyId3 = string;
export type StrategyRevision2 = number;
export type CapturedAt1 = string;
export type CaseId10 = string;
export type ContentHash = string;
export type ContractType10 = "evidence";
export type EvidenceId = string;
export type MediaType = string | null;
export type ObservedAt = string;
export type SchemaVersion10 = "1.0";
export type SourceRef = string;
export type CandidateModelTraceId = string | null;
export type CaseId11 = string;
export type CaseRevision4 = number;
export type CompletionId = string;
export type ContractType11 = "completion_decision";
export type CompletionOutcome = "continue" | "needs_user" | "needs_replan" | "candidate_complete" | "complete";
export type EvaluatedAt = string;
export type EvidenceIds3 = string[];
export type MissingEvidence = string[];
export type ReasonCodes = string[];
export type Revision9 = number;
export type SchemaVersion11 = "1.0";
export type VerifierName = string;
export type VerifierVersion = string;
export type AdapterVersion = string;
export type CaseId12 = string;
export type CompletedAt = string;
export type ContractType12 = "model_trace";
export type InputSchemaVersion = string;
export type InputTokens = number;
export type LatencyMs = number;
export type Model = string;
export type ModelVersion = string;
export type OutputRef = string | null;
export type OutputSchemaVersion = string;
export type OutputTokens = number;
export type PromptVersion = string;
export type Provider = string;
export type ModelResult = "succeeded" | "rejected" | "failed";
export type Revision10 = number;
export type SafetyFlags = string[];
export type SchemaVersion12 = "1.0";
export type StartedAt = string;
export type TraceId = string;

export interface Case {
  bill_snapshot?: BillSnapshot | null;
  case_id: CaseId1;
  constraint_set_revision: ConstraintSetRevision;
  constraints: Constraints;
  consumer_id: ConsumerId;
  contract_type: ContractType2;
  created_at: CreatedAt;
  delegated_authority: DelegatedAuthority;
  goal: ConsumerGoal;
  phase: CasePhase;
  revision: Revision3;
  schema_version: SchemaVersion3;
  updated_at: UpdatedAt1;
}
export interface BillSnapshot {
  add_ons: AddOns;
  captured_at: CapturedAt;
  case_id: CaseId;
  contract_type: ContractType;
  evidence_ids: EvidenceIds;
  line_items: LineItems;
  monthly_total: Money;
  revision: Revision;
  schema_version: SchemaVersion;
  snapshot_id: SnapshotId;
  term_months: TermMonths;
  usage: UsageProfile;
}
export interface LineItem {
  amount: Money;
  category: LineItemCategory;
  name: Name;
}
export interface Money {
  amount_minor: AmountMinor;
  currency: Currency;
}
export interface UsageProfile {
  data_megabytes: DataMegabytes;
  sms_count: SmsCount;
  voice_minutes: VoiceMinutes;
}
export interface Constraint {
  case_id: CaseId2;
  classification: ConstraintClassification;
  constraint_id: ConstraintId;
  contract_type: ContractType1;
  priority?: Priority;
  revision: Revision1;
  schema_version: SchemaVersion1;
  source: Source;
  statement: Statement;
  valid_from: ValidFrom;
  valid_until?: ValidUntil;
}
export interface DelegatedAuthority {
  allowed_actions: AllowedActions;
  allowed_disclosures: AllowedDisclosures;
  approval_required_actions: ApprovalRequiredActions;
}
export interface ConsumerGoal {
  case_id: CaseId3;
  contract_type: ContractType3;
  created_at: CreatedAt1;
  deadline?: Deadline;
  desired_outcome: DesiredOutcome;
  forbidden_changes: ForbiddenChanges;
  goal_id: GoalId;
  required_features: RequiredFeatures;
  revision: Revision2;
  schema_version: SchemaVersion2;
  target_monthly_total?: Money | null;
  updated_at: UpdatedAt;
}
export interface FactLedger {
  case_id: CaseId4;
  contract_type: ContractType4;
  created_at: CreatedAt2;
  entries: Entries;
  ledger_id: LedgerId;
  revision: Revision4;
  schema_version: SchemaVersion4;
  updated_at: UpdatedAt2;
}
export interface FactRecord {
  confidence: Confidence;
  evidence_ids?: EvidenceIds1;
  fact_id: FactId;
  key: Key;
  recorded_at: RecordedAt;
  source_message_id?: SourceMessageId;
  status: FactStatus;
  value: FactValue;
}
export interface StrategyPacket {
  allowed_disclosures: AllowedDisclosures1;
  approval_required_disclosures: ApprovalRequiredDisclosures;
  case_id: CaseId5;
  case_revision: CaseRevision;
  concession_ladder: ConcessionLadder;
  contract_type: ContractType5;
  created_at: CreatedAt3;
  current_subgoal: CurrentSubgoal;
  escalation_conditions: EscalationConditions;
  expires_at: ExpiresAt;
  fact_ledger_revision: FactLedgerRevision;
  fallback_outcomes: FallbackOutcomes;
  hard_constraint_ids: HardConstraintIds;
  primary_objective: PrimaryObjective;
  ranked_preference_ids: RankedPreferenceIds;
  replan_conditions: ReplanConditions;
  required_completion_evidence: RequiredCompletionEvidence;
  revision: Revision5;
  schema_version: SchemaVersion5;
  strategy_id: StrategyId;
}
export interface EvidenceRequirement {
  description: Description;
  evidence_type: EvidenceType;
}
export interface FastTurnDecision {
  action_intent?: ActionIntent | null;
  case_id: CaseId7;
  case_revision: CaseRevision2;
  completion_claim: CompletionClaim;
  contract_type: ContractType7;
  created_at: CreatedAt5;
  decision_id: DecisionId;
  dialogue_act: DialogueAct;
  fact_updates: FactUpdates;
  reasoner_request: ReasonerRequest;
  response_text: ResponseText;
  schema_version: SchemaVersion7;
  strategy_id: StrategyId2;
  strategy_revision: StrategyRevision1;
}
export interface ActionIntent {
  action_type: ActionType;
  approval_required: ApprovalRequired;
  authorization_state?: AuthorizationState;
  case_id: CaseId6;
  case_revision: CaseRevision1;
  constraint_set_revision: ConstraintSetRevision1;
  contract_type: ContractType6;
  created_at: CreatedAt4;
  expires_at?: ExpiresAt1;
  idempotency_key: IdempotencyKey;
  intent_id: IntentId;
  material_terms: MaterialTerms;
  material_terms_hash: MaterialTermsHash;
  offer_ref?: OfferReference | null;
  revision: Revision6;
  schema_version: SchemaVersion6;
  strategy_id: StrategyId1;
  strategy_revision: StrategyRevision;
}
export interface MaterialTerm {
  name: Name1;
  value: Value;
}
export interface OfferReference {
  offer_id: OfferId;
  offer_revision: OfferRevision;
}
export interface CompletionClaim {
  evidence_message_ids: EvidenceMessageIds;
  status: Status;
}
export interface FactUpdate {
  confidence: Confidence1;
  key: Key1;
  source_message_id: SourceMessageId1;
  status?: Status1;
  value: FactValue;
}
export interface ReasonerRequest {
  needed: Needed;
  reason_code: ReasonCode;
}
export interface ProviderOffer {
  case_id: CaseId8;
  contract_type: ContractType8;
  created_at: CreatedAt6;
  evidence_ids: EvidenceIds2;
  expires_at: ExpiresAt2;
  features: Features;
  fees: Fees;
  monthly_price: Money;
  offer_id: OfferId1;
  provider_id: ProviderId;
  revision: Revision7;
  schema_version: SchemaVersion8;
  term_months: TermMonths1;
  total_cost: Money;
}
export interface ApprovalRequest {
  action_intent_id: ActionIntentId;
  action_intent_revision: ActionIntentRevision;
  action_type: ActionType;
  approval_id: ApprovalId;
  case_id: CaseId9;
  case_revision: CaseRevision3;
  constraint_set_revision: ConstraintSetRevision2;
  contract_type: ContractType9;
  decided_at?: DecidedAt;
  decision?: ApprovalDecision;
  expires_at: ExpiresAt3;
  material_terms_hash: MaterialTermsHash1;
  offer_ref?: OfferReference | null;
  requested_at: RequestedAt;
  revision: Revision8;
  schema_version: SchemaVersion9;
  strategy_id: StrategyId3;
  strategy_revision: StrategyRevision2;
}
export interface Evidence {
  captured_at: CapturedAt1;
  case_id: CaseId10;
  content_hash: ContentHash;
  contract_type: ContractType10;
  evidence_id: EvidenceId;
  media_type?: MediaType;
  observed_at: ObservedAt;
  schema_version: SchemaVersion10;
  source_ref: SourceRef;
  source_type: EvidenceType;
}
export interface CompletionDecision {
  candidate_model_trace_id?: CandidateModelTraceId;
  case_id: CaseId11;
  case_revision: CaseRevision4;
  completion_id: CompletionId;
  contract_type: ContractType11;
  decision: CompletionOutcome;
  evaluated_at: EvaluatedAt;
  evidence_ids: EvidenceIds3;
  missing_evidence: MissingEvidence;
  reason_codes: ReasonCodes;
  revision: Revision9;
  schema_version: SchemaVersion11;
  verifier_name: VerifierName;
  verifier_version: VerifierVersion;
}
export interface ModelTrace {
  adapter_version: AdapterVersion;
  case_id: CaseId12;
  completed_at: CompletedAt;
  contract_type: ContractType12;
  input_schema_version: InputSchemaVersion;
  input_tokens: InputTokens;
  latency_ms: LatencyMs;
  model: Model;
  model_version: ModelVersion;
  output_ref?: OutputRef;
  output_schema_version: OutputSchemaVersion;
  output_tokens: OutputTokens;
  prompt_version: PromptVersion;
  provider: Provider;
  result: ModelResult;
  revision: Revision10;
  safety_flags: SafetyFlags;
  schema_version: SchemaVersion12;
  started_at: StartedAt;
  trace_id: TraceId;
}
