/* Generated by `make contracts`; do not edit by hand. Verify with `make contracts-check`. Canonical source: proxyloop_contracts. */

/**
 * Canonical Phase 00B wire contracts generated from the framework-independent Pydantic package.
 */
export type ProxyLoopContractDocument =
  | Case
  | ConsumerGoal
  | Constraint
  | BillSnapshot
  | FactLedger
  | StrategyPacket
  | FastTurnDecision
  | ProviderOffer
  | ActionIntent
  | ApprovalRequest
  | Evidence
  | CompletionDecision
  | ModelTrace
  | ModelInputPins
  | PlanningBasis
  | VisibleCaseEvent
  | CapabilityManifest
  | CaseContextSnapshot
  | FastModelView
  | SlowReasonerView
  | RoutingDecision
  | SlowWorkRequest
  | SlowWorkResult;
export type AddOns = string[];
export type CapturedAt = string;
export type CaseId = string;
export type ContractType = "bill_snapshot";
export type EvidenceIds = string[];
export type AmountMinor = number;
export type Currency = string;
export type LineItemCategory = "service" | "addon" | "fee" | "tax" | "credit";
export type Name = string;
export type LineItems = LineItem[];
export type Revision = number;
export type SchemaVersion = "1.0";
export type SnapshotId = string;
export type TermMonths = number;
export type DataMegabytes = number;
export type SmsCount = number;
export type VoiceMinutes = number;
export type CaseId1 = string;
export type ConstraintSetRevision = number;
export type CaseId2 = string;
export type ConstraintClassification = "hard" | "soft";
export type ConstraintId = string;
export type ContractType1 = "constraint";
export type Priority = number | null;
export type Revision1 = number;
export type SchemaVersion1 = "1.0";
export type Source = string;
export type Statement = string;
export type ValidFrom = string;
export type ValidUntil = string | null;
export type Constraints = Constraint[];
export type ConsumerId = string;
export type ContractType2 = "case";
export type CreatedAt = string;
export type ActionType =
  "send_message" | "request_clarification" | "disclose_information" | "accept_offer" | "end_interaction";
export type AllowedActions = ActionType[];
export type AllowedDisclosures = string[];
export type ApprovalRequiredActions = ActionType[];
export type CaseId3 = string;
export type ContractType3 = "consumer_goal";
export type CreatedAt1 = string;
export type Deadline = string | null;
export type DesiredOutcome = string;
export type ForbiddenChanges = string[];
export type GoalId = string;
export type RequiredFeatures = string[];
export type Revision2 = number;
export type SchemaVersion2 = "1.0";
export type UpdatedAt = string;
export type CasePhase =
  "initiated" | "strategy" | "negotiating" | "awaiting_approval" | "candidate_complete" | "complete" | "closed";
export type Revision3 = number;
export type SchemaVersion3 = "1.0";
export type UpdatedAt1 = string;
export type CaseId4 = string;
export type ContractType4 = "fact_ledger";
export type CreatedAt2 = string;
export type Confidence = number;
export type EvidenceIds1 = string[];
export type FactId = string;
export type Key = string;
export type RecordedAt = string;
export type SourceMessageId = string | null;
export type FactStatus = "candidate" | "verified" | "rejected";
export type FactValue = Money | string | number | boolean;
export type Entries = FactRecord[];
export type LedgerId = string;
export type Revision4 = number;
export type SchemaVersion4 = "1.0";
export type UpdatedAt2 = string;
export type AllowedDisclosures1 = string[];
export type ApprovalRequiredDisclosures = string[];
export type CaseId5 = string;
export type CaseRevision = number;
export type ConcessionLadder = string[];
export type ContractType5 = "strategy_packet";
export type CreatedAt3 = string;
export type CurrentSubgoal = string;
export type EscalationConditions = string[];
export type ExpiresAt = string;
export type FactLedgerRevision = number;
export type FallbackOutcomes = string[];
export type HardConstraintIds = string[];
export type PrimaryObjective = string;
export type RankedPreferenceIds = string[];
export type ReplanConditions = string[];
export type Description = string;
export type EvidenceType = "provider_message" | "provider_event" | "confirmation" | "bill" | "simulator_transition";
export type RequiredCompletionEvidence = EvidenceRequirement[];
export type Revision5 = number;
export type SchemaVersion5 = "1.0";
export type StrategyId = string;
export type ApprovalRequired = boolean;
export type AuthorizationState = "proposed";
export type CaseId6 = string;
export type CaseRevision1 = number;
export type ConstraintSetRevision1 = number;
export type ContractType6 = "action_intent";
export type CreatedAt4 = string;
export type ExpiresAt1 = string | null;
export type IdempotencyKey = string;
export type IntentId = string;
export type Name1 = string;
export type Value = string;
export type MaterialTerms = MaterialTerm[];
export type MaterialTermsHash = string;
export type OfferId = string;
export type OfferRevision = number;
export type Revision6 = number;
export type SchemaVersion6 = "1.0";
export type StrategyId1 = string;
export type StrategyRevision = number;
export type CaseId7 = string;
export type CaseRevision2 = number;
export type EvidenceMessageIds = string[];
export type Status = "not_done" | "candidate";
export type ContractType7 = "fast_turn_decision";
export type CreatedAt5 = string;
export type DecisionId = string;
export type DialogueAct = "clarify" | "counter" | "confirm" | "challenge" | "escalate" | "close";
export type Confidence1 = number;
export type Key1 = string;
export type SourceMessageId1 = string;
export type Status1 = "candidate";
export type FactUpdates = FactUpdate[];
export type Needed = boolean;
export type ReasonCode = string;
export type ResponseText = string;
export type SchemaVersion7 = "1.0";
export type StrategyId2 = string;
export type StrategyRevision1 = number;
export type CaseId8 = string;
export type ContractType8 = "provider_offer";
export type CreatedAt6 = string;
export type EvidenceIds2 = string[];
export type ExpiresAt2 = string;
export type Features = string[];
export type Fees = LineItem[];
export type OfferId1 = string;
export type ProviderId = string;
export type Revision7 = number;
export type SchemaVersion8 = "1.0";
export type TermMonths1 = number;
export type ActionIntentId = string;
export type ActionIntentRevision = number;
export type ApprovalId = string;
export type CaseId9 = string;
export type CaseRevision3 = number;
export type ConstraintSetRevision2 = number;
export type ContractType9 = "approval_request";
export type DecidedAt = string | null;
export type ApprovalDecision = "pending" | "approved" | "rejected" | "expired";
export type ExpiresAt3 = string;
export type MaterialTermsHash1 = string;
export type RequestedAt = string;
export type Revision8 = number;
export type SchemaVersion9 = "1.0";
export type StrategyId3 = string;
export type StrategyRevision2 = number;
export type CapturedAt1 = string;
export type CaseId10 = string;
export type ContentHash = string;
export type ContractType10 = "evidence";
export type EvidenceId = string;
export type MediaType = string | null;
export type ObservedAt = string;
export type SchemaVersion10 = "1.0";
export type SourceRef = string;
export type CandidateModelTraceId = string | null;
export type CaseId11 = string;
export type CaseRevision4 = number;
export type CompletionId = string;
export type ContractType11 = "completion_decision";
export type CompletionOutcome = "continue" | "needs_user" | "needs_replan" | "candidate_complete" | "complete";
export type EvaluatedAt = string;
export type EvidenceIds3 = string[];
export type MissingEvidence = string[];
export type ReasonCodes = string[];
export type Revision9 = number;
export type SchemaVersion11 = "1.0";
export type VerifierName = string;
export type VerifierVersion = string;
export type AdapterVersion = string;
export type CaseId12 = string;
export type CompletedAt = string;
export type ContractType12 = "model_trace";
export type InputSchemaVersion = string;
export type InputTokens = number;
export type LatencyMs = number;
export type Model = string;
export type ModelVersion = string;
export type OutputRef = string | null;
export type OutputSchemaVersion = string;
export type OutputTokens = number;
export type PromptVersion = string;
export type Provider = string;
export type ModelResult = "succeeded" | "rejected" | "failed";
export type Revision10 = number;
export type SafetyFlags = string[];
export type SchemaVersion12 = "1.0";
export type StartedAt = string;
export type TraceId = string;
export type CapabilityManifestVersion = string;
export type CaseId13 = string;
export type CaseRevision5 = number;
export type ConstraintSetRevision3 = number;
export type ContractType13 = "model_input_pins";
export type EventCursor = number;
export type FactLedgerRevision1 = number;
export type PlanningBasisFingerprint = string;
export type ProviderConfigRef = string;
export type Revision11 = number;
export type SchemaVersion13 = "1.0";
export type StrategyId4 = string | null;
export type StrategyRevision3 = number;
export type ApprovalStateFingerprint = string;
export type CapabilityManifestFingerprint = string;
export type ConstraintsFingerprint = string;
export type ContractType14 = "planning_basis";
export type DelegatedAuthorityFingerprint = string;
export type GoalFingerprint = string;
export type MaterialOffersFingerprint = string;
export type PlanningBasisFingerprint1 = string;
export type ProviderConfigFingerprint = string;
export type Revision12 = number;
export type SchemaVersion14 = "1.0";
export type VerifiedFactsFingerprint = string;
export type EventActor = "consumer" | "provider" | "system";
export type CaseId14 = string;
export type Content = string;
export type ContractType15 = "visible_case_event";
export type EventCursor1 = number;
export type EventId = string;
export type EventType = string;
export type OccurredAt = string;
export type Revision13 = number;
export type SchemaVersion15 = "1.0";
export type AllowedActionTypes = ActionType[];
export type CapabilityId = string;
export type Description1 = string;
export type ExpiresAt4 = string | null;
export type Namespace = "simulator";
export type Version = string;
export type Capabilities = CapabilityDefinition[];
export type ContractType16 = "capability_manifest";
export type ExpiresAt5 = string;
export type IssuedAt = string;
export type ManifestVersion = string;
export type Namespace1 = "simulator";
export type Revision14 = number;
export type SchemaVersion16 = "1.0";
export type ActionIntents = ActionIntent[];
export type ApprovalRequests = ApprovalRequest[];
export type ContractType17 = "case_context_snapshot";
export type EventCursor2 = number;
export type Evidence1 = Evidence[];
export type Offers = ProviderOffer[];
export type PendingExecution = boolean;
export type PendingSlowWork = boolean;
export type ProviderConfigRef1 = string;
export type Revision15 = number;
export type SchemaVersion17 = "1.0";
export type VisibleEvents = VisibleCaseEvent[];
export type AllowedDialogueActs = DialogueAct[];
export type AllowedDisclosures2 = string[];
export type CaseId15 = string;
export type Constraints1 = Constraint[];
export type ContractType18 = "fast_model_view";
export type PendingSlowWork1 = boolean;
export type RecentEvents = VisibleCaseEvent[];
export type Revision16 = number;
export type SchemaVersion18 = "1.0";
export type VerifiedFacts = FactRecord[];
export type ApprovalRequests1 = ApprovalRequest[];
export type CaseId16 = string;
export type Constraints2 = Constraint[];
export type ContractType19 = "slow_reasoner_view";
export type Offers1 = ProviderOffer[];
export type ProviderConfigRef2 = string;
export type ReasonCode1 = string;
export type RecentEvents1 = VisibleCaseEvent[];
export type Revision17 = number;
export type SchemaVersion19 = "1.0";
export type VerifiedFacts1 = FactRecord[];
export type ContractType20 = "routing_decision";
export type CreatedAt7 = string;
export type RoutingOutcome =
  "terminal" | "verify_only" | "wait_for_approval" | "slow_refresh" | "fast_now_and_slow_refresh" | "fast_now";
export type ReasonCodes1 = string[];
export type Revision18 = number;
export type SchemaVersion20 = "1.0";
export type CaseId17 = string;
export type ContractType21 = "slow_work_request";
export type CreatedAt8 = string;
export type ReasonCode2 = string;
export type RequestId = string;
export type Revision19 = number;
export type SchemaVersion21 = "1.0";
export type ActionProposals = ActionIntent[];
export type Name2 = string;
export type Arguments = CapabilityArgument[];
export type CapabilityId1 = string;
export type Namespace2 = "simulator";
export type Version1 = string;
export type CreatedAt9 = string;
export type ExpiresAt6 = string | null;
export type ProposalId = string;
export type CapabilityProposals = CapabilityProposal[];
export type CaseId18 = string;
export type ContractType22 = "slow_work_result";
export type CreatedAt10 = string;
export type RequestId1 = string;
export type ResultId = string;
export type Revision20 = number;
export type SchemaVersion22 = "1.0";

export interface Case {
  bill_snapshot?: BillSnapshot | null;
  case_id: CaseId1;
  constraint_set_revision: ConstraintSetRevision;
  constraints: Constraints;
  consumer_id: ConsumerId;
  contract_type: ContractType2;
  created_at: CreatedAt;
  delegated_authority: DelegatedAuthority;
  goal: ConsumerGoal;
  phase: CasePhase;
  revision: Revision3;
  schema_version: SchemaVersion3;
  updated_at: UpdatedAt1;
}
export interface BillSnapshot {
  add_ons: AddOns;
  captured_at: CapturedAt;
  case_id: CaseId;
  contract_type: ContractType;
  evidence_ids: EvidenceIds;
  line_items: LineItems;
  monthly_total: Money;
  revision: Revision;
  schema_version: SchemaVersion;
  snapshot_id: SnapshotId;
  term_months: TermMonths;
  usage: UsageProfile;
}
export interface LineItem {
  amount: Money;
  category: LineItemCategory;
  name: Name;
}
export interface Money {
  amount_minor: AmountMinor;
  currency: Currency;
}
export interface UsageProfile {
  data_megabytes: DataMegabytes;
  sms_count: SmsCount;
  voice_minutes: VoiceMinutes;
}
export interface Constraint {
  case_id: CaseId2;
  classification: ConstraintClassification;
  constraint_id: ConstraintId;
  contract_type: ContractType1;
  priority?: Priority;
  revision: Revision1;
  schema_version: SchemaVersion1;
  source: Source;
  statement: Statement;
  valid_from: ValidFrom;
  valid_until?: ValidUntil;
}
export interface DelegatedAuthority {
  allowed_actions: AllowedActions;
  allowed_disclosures: AllowedDisclosures;
  approval_required_actions: ApprovalRequiredActions;
}
export interface ConsumerGoal {
  case_id: CaseId3;
  contract_type: ContractType3;
  created_at: CreatedAt1;
  deadline?: Deadline;
  desired_outcome: DesiredOutcome;
  forbidden_changes: ForbiddenChanges;
  goal_id: GoalId;
  required_features: RequiredFeatures;
  revision: Revision2;
  schema_version: SchemaVersion2;
  target_monthly_total?: Money | null;
  updated_at: UpdatedAt;
}
export interface FactLedger {
  case_id: CaseId4;
  contract_type: ContractType4;
  created_at: CreatedAt2;
  entries: Entries;
  ledger_id: LedgerId;
  revision: Revision4;
  schema_version: SchemaVersion4;
  updated_at: UpdatedAt2;
}
export interface FactRecord {
  confidence: Confidence;
  evidence_ids?: EvidenceIds1;
  fact_id: FactId;
  key: Key;
  recorded_at: RecordedAt;
  source_message_id?: SourceMessageId;
  status: FactStatus;
  value: FactValue;
}
export interface StrategyPacket {
  allowed_disclosures: AllowedDisclosures1;
  approval_required_disclosures: ApprovalRequiredDisclosures;
  case_id: CaseId5;
  case_revision: CaseRevision;
  concession_ladder: ConcessionLadder;
  contract_type: ContractType5;
  created_at: CreatedAt3;
  current_subgoal: CurrentSubgoal;
  escalation_conditions: EscalationConditions;
  expires_at: ExpiresAt;
  fact_ledger_revision: FactLedgerRevision;
  fallback_outcomes: FallbackOutcomes;
  hard_constraint_ids: HardConstraintIds;
  primary_objective: PrimaryObjective;
  ranked_preference_ids: RankedPreferenceIds;
  replan_conditions: ReplanConditions;
  required_completion_evidence: RequiredCompletionEvidence;
  revision: Revision5;
  schema_version: SchemaVersion5;
  strategy_id: StrategyId;
}
export interface EvidenceRequirement {
  description: Description;
  evidence_type: EvidenceType;
}
export interface FastTurnDecision {
  action_intent?: ActionIntent | null;
  case_id: CaseId7;
  case_revision: CaseRevision2;
  completion_claim: CompletionClaim;
  contract_type: ContractType7;
  created_at: CreatedAt5;
  decision_id: DecisionId;
  dialogue_act: DialogueAct;
  fact_updates: FactUpdates;
  reasoner_request: ReasonerRequest;
  response_text: ResponseText;
  schema_version: SchemaVersion7;
  strategy_id: StrategyId2;
  strategy_revision: StrategyRevision1;
}
export interface ActionIntent {
  action_type: ActionType;
  approval_required: ApprovalRequired;
  authorization_state?: AuthorizationState;
  case_id: CaseId6;
  case_revision: CaseRevision1;
  constraint_set_revision: ConstraintSetRevision1;
  contract_type: ContractType6;
  created_at: CreatedAt4;
  expires_at?: ExpiresAt1;
  idempotency_key: IdempotencyKey;
  intent_id: IntentId;
  material_terms: MaterialTerms;
  material_terms_hash: MaterialTermsHash;
  offer_ref?: OfferReference | null;
  revision: Revision6;
  schema_version: SchemaVersion6;
  strategy_id: StrategyId1;
  strategy_revision: StrategyRevision;
}
export interface MaterialTerm {
  name: Name1;
  value: Value;
}
export interface OfferReference {
  offer_id: OfferId;
  offer_revision: OfferRevision;
}
export interface CompletionClaim {
  evidence_message_ids: EvidenceMessageIds;
  status: Status;
}
export interface FactUpdate {
  confidence: Confidence1;
  key: Key1;
  source_message_id: SourceMessageId1;
  status?: Status1;
  value: FactValue;
}
export interface ReasonerRequest {
  needed: Needed;
  reason_code: ReasonCode;
}
export interface ProviderOffer {
  case_id: CaseId8;
  contract_type: ContractType8;
  created_at: CreatedAt6;
  evidence_ids: EvidenceIds2;
  expires_at: ExpiresAt2;
  features: Features;
  fees: Fees;
  monthly_price: Money;
  offer_id: OfferId1;
  provider_id: ProviderId;
  revision: Revision7;
  schema_version: SchemaVersion8;
  term_months: TermMonths1;
  total_cost: Money;
}
export interface ApprovalRequest {
  action_intent_id: ActionIntentId;
  action_intent_revision: ActionIntentRevision;
  action_type: ActionType;
  approval_id: ApprovalId;
  case_id: CaseId9;
  case_revision: CaseRevision3;
  constraint_set_revision: ConstraintSetRevision2;
  contract_type: ContractType9;
  decided_at?: DecidedAt;
  decision?: ApprovalDecision;
  expires_at: ExpiresAt3;
  material_terms_hash: MaterialTermsHash1;
  offer_ref?: OfferReference | null;
  requested_at: RequestedAt;
  revision: Revision8;
  schema_version: SchemaVersion9;
  strategy_id: StrategyId3;
  strategy_revision: StrategyRevision2;
}
export interface Evidence {
  captured_at: CapturedAt1;
  case_id: CaseId10;
  content_hash: ContentHash;
  contract_type: ContractType10;
  evidence_id: EvidenceId;
  media_type?: MediaType;
  observed_at: ObservedAt;
  schema_version: SchemaVersion10;
  source_ref: SourceRef;
  source_type: EvidenceType;
}
export interface CompletionDecision {
  candidate_model_trace_id?: CandidateModelTraceId;
  case_id: CaseId11;
  case_revision: CaseRevision4;
  completion_id: CompletionId;
  contract_type: ContractType11;
  decision: CompletionOutcome;
  evaluated_at: EvaluatedAt;
  evidence_ids: EvidenceIds3;
  missing_evidence: MissingEvidence;
  reason_codes: ReasonCodes;
  revision: Revision9;
  schema_version: SchemaVersion11;
  verifier_name: VerifierName;
  verifier_version: VerifierVersion;
}
export interface ModelTrace {
  adapter_version: AdapterVersion;
  case_id: CaseId12;
  completed_at: CompletedAt;
  contract_type: ContractType12;
  input_schema_version: InputSchemaVersion;
  input_tokens: InputTokens;
  latency_ms: LatencyMs;
  model: Model;
  model_version: ModelVersion;
  output_ref?: OutputRef;
  output_schema_version: OutputSchemaVersion;
  output_tokens: OutputTokens;
  prompt_version: PromptVersion;
  provider: Provider;
  result: ModelResult;
  revision: Revision10;
  safety_flags: SafetyFlags;
  schema_version: SchemaVersion12;
  started_at: StartedAt;
  trace_id: TraceId;
}
/**
 * The complete version pin set accepted by a model adapter.
 */
export interface ModelInputPins {
  capability_manifest_version: CapabilityManifestVersion;
  case_id: CaseId13;
  case_revision: CaseRevision5;
  constraint_set_revision: ConstraintSetRevision3;
  contract_type: ContractType13;
  event_cursor: EventCursor;
  fact_ledger_revision: FactLedgerRevision1;
  planning_basis_fingerprint: PlanningBasisFingerprint;
  provider_config_ref: ProviderConfigRef;
  revision: Revision11;
  schema_version: SchemaVersion13;
  strategy_id?: StrategyId4;
  strategy_revision?: StrategyRevision3;
}
/**
 * Strongly typed fingerprints for every material strategy input.
 */
export interface PlanningBasis {
  approval_state_fingerprint: ApprovalStateFingerprint;
  capability_manifest_fingerprint: CapabilityManifestFingerprint;
  constraints_fingerprint: ConstraintsFingerprint;
  contract_type: ContractType14;
  delegated_authority_fingerprint: DelegatedAuthorityFingerprint;
  goal_fingerprint: GoalFingerprint;
  material_offers_fingerprint: MaterialOffersFingerprint;
  planning_basis_fingerprint: PlanningBasisFingerprint1;
  provider_config_fingerprint: ProviderConfigFingerprint;
  revision: Revision12;
  schema_version: SchemaVersion14;
  verified_facts_fingerprint: VerifiedFactsFingerprint;
}
/**
 * A leakage-safe event that may be projected to a model.
 */
export interface VisibleCaseEvent {
  actor: EventActor;
  case_id: CaseId14;
  content: Content;
  contract_type: ContractType15;
  event_cursor: EventCursor1;
  event_id: EventId;
  event_type: EventType;
  occurred_at: OccurredAt;
  revision: Revision13;
  schema_version: SchemaVersion15;
}
/**
 * The sole, simulator-only action vocabulary visible to models.
 */
export interface CapabilityManifest {
  capabilities: Capabilities;
  contract_type: ContractType16;
  expires_at: ExpiresAt5;
  issued_at: IssuedAt;
  manifest_version: ManifestVersion;
  namespace: Namespace1;
  revision: Revision14;
  schema_version: SchemaVersion16;
}
/**
 * One simulator capability advertised by a manifest.
 */
export interface CapabilityDefinition {
  allowed_action_types: AllowedActionTypes;
  capability_id: CapabilityId;
  description: Description1;
  expires_at?: ExpiresAt4;
  namespace?: Namespace;
  version: Version;
}
/**
 * Immutable model-external Case state at one event cursor.
 */
export interface CaseContextSnapshot {
  action_intents?: ActionIntents;
  approval_requests?: ApprovalRequests;
  capability_manifest: CapabilityManifest;
  case: Case;
  completion_decision?: CompletionDecision | null;
  contract_type: ContractType17;
  event_cursor: EventCursor2;
  evidence?: Evidence1;
  fact_ledger: FactLedger;
  offers?: Offers;
  pending_execution?: PendingExecution;
  pending_slow_work?: PendingSlowWork;
  pins: ModelInputPins;
  planning_basis: PlanningBasis;
  provider_config_ref: ProviderConfigRef1;
  revision: Revision15;
  schema_version: SchemaVersion17;
  strategy?: StrategyPacket | null;
  visible_events?: VisibleEvents;
}
/**
 * Explicit allowlist for the low-latency model.
 */
export interface FastModelView {
  allowed_dialogue_acts: AllowedDialogueActs;
  allowed_disclosures: AllowedDisclosures2;
  case_id: CaseId15;
  constraints: Constraints1;
  contract_type: ContractType18;
  goal: ConsumerGoal;
  latest_provider_event?: VisibleCaseEvent | null;
  pending_slow_work?: PendingSlowWork1;
  pins: ModelInputPins;
  planning_basis: PlanningBasis;
  recent_events?: RecentEvents;
  revision: Revision16;
  schema_version: SchemaVersion18;
  strategy?: StrategyPacket | null;
  verified_facts: VerifiedFacts;
}
/**
 * Explicit allowlist for the bounded Slow reasoner.
 */
export interface SlowReasonerView {
  approval_requests?: ApprovalRequests1;
  capability_manifest: CapabilityManifest;
  case_id: CaseId16;
  constraints: Constraints2;
  contract_type: ContractType19;
  delegated_authority: DelegatedAuthority;
  goal: ConsumerGoal;
  offers?: Offers1;
  pins: ModelInputPins;
  planning_basis: PlanningBasis;
  provider_config_ref: ProviderConfigRef2;
  reason_code: ReasonCode1;
  recent_events?: RecentEvents1;
  revision: Revision17;
  schema_version: SchemaVersion19;
  strategy?: StrategyPacket | null;
  verified_facts: VerifiedFacts1;
}
export interface RoutingDecision {
  contract_type: ContractType20;
  created_at: CreatedAt7;
  outcome: RoutingOutcome;
  pins: ModelInputPins;
  reason_codes: ReasonCodes1;
  revision: Revision18;
  schema_version: SchemaVersion20;
}
export interface SlowWorkRequest {
  case_id: CaseId17;
  contract_type: ContractType21;
  created_at: CreatedAt8;
  pins: ModelInputPins;
  planning_basis: PlanningBasis;
  reason_code: ReasonCode2;
  request_id: RequestId;
  revision: Revision19;
  schema_version: SchemaVersion21;
  view: SlowReasonerView;
}
export interface SlowWorkResult {
  action_proposals?: ActionProposals;
  capability_proposals?: CapabilityProposals;
  case_id: CaseId18;
  contract_type: ContractType22;
  created_at: CreatedAt10;
  pins: ModelInputPins;
  planning_basis: PlanningBasis;
  request_id: RequestId1;
  result_id: ResultId;
  revision: Revision20;
  schema_version: SchemaVersion22;
  strategy_proposal?: StrategyPacket | null;
}
/**
 * A model proposal; it has no authorization or execution authority.
 */
export interface CapabilityProposal {
  arguments?: Arguments;
  capability: CapabilityReference;
  created_at: CreatedAt9;
  expires_at?: ExpiresAt6;
  proposal_id: ProposalId;
}
export interface CapabilityArgument {
  name: Name2;
  value: FactValue;
}
export interface CapabilityReference {
  capability_id: CapabilityId1;
  namespace: Namespace2;
  version: Version1;
}
