#!/usr/bin/env python3
"""Generate and verify the committed Phase 00B contract artifacts."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

from proxyloop_contracts import contract_json_schema

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_RELATIVE = Path("contracts/jsonschema/proxyloop-contracts.schema.json")
TYPES_RELATIVE = Path("contracts/typescript/proxyloop-contracts.d.ts")
FIXTURE_RELATIVE = Path("contracts/typescript/valid-case.fixture.ts")
SOURCE_FIXTURE = ROOT / "tests/fixtures/case.valid.json"
GENERATED_FILES = (SCHEMA_RELATIVE, TYPES_RELATIVE, FIXTURE_RELATIVE)
GENERATED_BANNER = (
    "/* Generated by `make contracts`; do not edit by hand. "
    "Verify with `make contracts-check`. Canonical source: proxyloop_contracts. */"
)


def render_schema(destination: Path) -> None:
    schema = contract_json_schema()
    schema.update(
        {
            "$id": "https://proxyloop.local/schemas/proxyloop-contracts-1.0.json",
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": "ProxyLoop Contract Document",
            "description": (
                "Canonical Phase 00B wire contracts generated from the "
                "framework-independent Pydantic package."
            ),
            "x-generated-by": "scripts/generate_contracts.py",
            "x-regeneration-command": "make contracts",
            "x-schema-version": "1.0",
            "x-source": "runtime/packages/contracts/src/proxyloop_contracts",
            "x-drift-command": "make contracts-check",
        }
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(schema, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def render_types(schema: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "pnpm",
            "exec",
            "json2ts",
            "-i",
            str(schema),
            "-o",
            str(destination),
            "--bannerComment",
            GENERATED_BANNER,
            "--no-enableConstEnums",
        ],
        cwd=ROOT,
        check=True,
    )


def render_fixture(destination: Path) -> None:
    fixture = json.loads(SOURCE_FIXTURE.read_text(encoding="utf-8"))
    fixture_literal = json.dumps(fixture, indent=2)
    export_line = f"export const validCase = {fixture_literal} as const satisfies Case;"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        "\n".join(
            (
                GENERATED_BANNER,
                "",
                "import type { Case } from './proxyloop-contracts';",
                "",
                export_line,
                "",
            )
        ),
        encoding="utf-8",
    )


def render_all(output_root: Path) -> None:
    schema = output_root / SCHEMA_RELATIVE
    render_schema(schema)
    render_types(schema, output_root / TYPES_RELATIVE)
    render_fixture(output_root / FIXTURE_RELATIVE)


def check_committed(generated_root: Path) -> int:
    mismatches: list[Path] = []
    for relative in GENERATED_FILES:
        committed = ROOT / relative
        generated = generated_root / relative
        if not committed.exists() or committed.read_bytes() != generated.read_bytes():
            mismatches.append(relative)

    if mismatches:
        print("Contract artifacts are missing or stale:")
        for relative in mismatches:
            print(f"  - {relative}")
        print("Run `make contracts` and commit the results.")
        return 1

    print("Contract artifacts match the canonical Pydantic source.")
    return 0


def write_committed(generated_root: Path) -> None:
    for relative in GENERATED_FILES:
        destination = ROOT / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(generated_root / relative, destination)
    print("Generated canonical JSON Schema and TypeScript contracts.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed generated artifacts differ from a fresh render",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    with tempfile.TemporaryDirectory(prefix="proxyloop-contracts-") as temp_dir:
        generated_root = Path(temp_dir)
        render_all(generated_root)
        if args.check:
            return check_committed(generated_root)
        write_committed(generated_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
