"""Shared Case application Runtime and persistence adapters."""

from .commands import (
    CASE_COMMAND_SCHEMA_VERSION,
    CHANNEL_COMMAND_SCHEMA_VERSION,
    CaseCommand,
    CaseCommandType,
    CaseTransitionRef,
)
from .postgres_repository import PostgresCaseRepository
from .repository import (
    CaseConflictError,
    CaseNotFoundError,
    CaseRepository,
    CaseRuntimeState,
    ChannelBindingRecord,
    ChannelConflictError,
    ChannelDependencyUnavailableError,
    DeliveryReceiptRecord,
    InboxReceiptRecord,
    InMemoryCaseRepository,
    OutboxRecord,
    StorageUnavailableError,
)
from .runtime import (
    ASSISTANT_MESSAGE_EVENT_TYPE,
    FAST_FALLBACK_TEXT,
    SCRIPTED_CASE_ID,
    AdapterMode,
    ModelRuntimeError,
    RuntimeProfile,
    RuntimeResult,
    StorageMode,
    ThinAgentRuntime,
)

__all__ = [
    "ASSISTANT_MESSAGE_EVENT_TYPE",
    "CASE_COMMAND_SCHEMA_VERSION",
    "CHANNEL_COMMAND_SCHEMA_VERSION",
    "FAST_FALLBACK_TEXT",
    "SCRIPTED_CASE_ID",
    "AdapterMode",
    "CaseCommand",
    "CaseCommandType",
    "CaseConflictError",
    "CaseNotFoundError",
    "CaseRepository",
    "CaseRuntimeState",
    "CaseTransitionRef",
    "ChannelBindingRecord",
    "ChannelConflictError",
    "ChannelDependencyUnavailableError",
    "DeliveryReceiptRecord",
    "InMemoryCaseRepository",
    "InboxReceiptRecord",
    "ModelRuntimeError",
    "OutboxRecord",
    "PostgresCaseRepository",
    "RuntimeProfile",
    "RuntimeResult",
    "StorageMode",
    "StorageUnavailableError",
    "ThinAgentRuntime",
]
